name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macOS-latest"]
    runs-on: ${{ matrix.os }}
    name: "Test on ${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --no-fail-fast --verbose
